import Link from "next/link";
import LogoMark from "@/components/LogoMark";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="notebook-bg flex min-h-screen flex-col">
      <header className="sticky top-0 z-20 flex items-center justify-between border-b border-chalk/10 bg-ink px-4 py-4 sm:px-6">
        <Link href="/" className="flex items-center gap-2 text-chalk-dim hover:text-chalk">
          <ArrowLeft size={18} />
          <span className="hidden text-sm sm:inline">Home</span>
        </Link>
        <span className="flex items-center gap-2 font-hand text-xl font-bold text-chalk sm:text-2xl">
          <LogoMark size={24} /> Terms of Service
        </span>
        <div className="w-[88px]" />
      </header>

      <main className="mx-auto flex w-full max-w-2xl flex-1 flex-col gap-5 px-4 py-10 text-sm leading-relaxed text-chalk-dim sm:px-6">
        <div className="rounded-xl border border-mustard/30 bg-mustard/10 px-4 py-3 text-xs text-chalk">
          This is a starting template, not legal advice. Before relying on this with real users
          and real data, have an actual lawyer review it - the specifics should reflect your
          real business, location, and legal obligations.
        </div>

        <p className="text-chalk-dim">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

        <section>
          <h2 className="mb-1 font-semibold text-chalk">1. Acceptance of terms</h2>
          <p>
            By creating an account or using Mentora AI, you agree to these Terms of Service. If
            you don&apos;t agree, please don&apos;t use the platform.
          </p>
        </section>

        <section>
          <h2 className="mb-1 font-semibold text-chalk">2. Who can use this</h2>
          <p>
            Mentora AI is intended for users 13 years of age or older. If you are under 18, you
            should have a parent or guardian&apos;s permission to use this platform.
          </p>
        </section>

        <section>
          <h2 className="mb-1 font-semibold text-chalk">3. Your account</h2>
          <p>
            You&apos;re responsible for the activity on your account and for keeping your login
            credentials secure. Authentication is handled by Clerk, a third-party service.
          </p>
        </section>

        <section>
          <h2 className="mb-1 font-semibold text-chalk">4. AI-generated content</h2>
          <p>
            Explanations, feedback, quiz grading, and interview responses are generated by AI
            models (including Google&apos;s Gemini). While we aim for accuracy, AI-generated
            content can contain mistakes. Use judgment, especially for anything safety-critical.
          </p>
        </section>

        <section>
          <h2 className="mb-1 font-semibold text-chalk">5. Certificates</h2>
          <p>
            The final exam certificate reflects performance on our own assessment. It is not an
            accredited or industry-recognized credential unless we explicitly state otherwise.
          </p>
        </section>

        <section>
          <h2 className="mb-1 font-semibold text-chalk">6. Acceptable use</h2>
          <p>
            Don&apos;t attempt to circumvent exam integrity measures, abuse rate limits, or use
            the platform to generate harmful, illegal, or abusive content.
          </p>
        </section>

        <section>
          <h2 className="mb-1 font-semibold text-chalk">7. Changes</h2>
          <p>
            We may update these terms as the platform evolves. Continued use after changes means
            you accept the updated terms.
          </p>
        </section>

        <section>
          <h2 className="mb-1 font-semibold text-chalk">8. Contact</h2>
          <p>Questions about these terms? Reach out at [your contact email].</p>
        </section>
      </main>
    </div>
  );
}
